server:
  port: 9080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth, /auth/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products, /products/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
              - Path=/orders, /orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

